services:
  web:
    build: .
    image: examen:v1
    ports:
      - "80:4500"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

